// <auto-generated />
using System;
using AIInterview.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIInterview.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620110718_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIInterview.Shared.Models.CheatEventModel", b =>
                {
                    b.Property<Guid>("CheatEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InterviewSessionModelsInterviewSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CheatEventId");

                    b.HasIndex("InterviewSessionId");

                    b.HasIndex("InterviewSessionModelsInterviewSessionId");

                    b.ToTable("CheatEvent", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.InterviewSessionModels", b =>
                {
                    b.Property<Guid>("InterviewSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CheatEventCount")
                        .HasColumnType("int");

                    b.Property<bool>("CheatFlagged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentModelStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("InterviewSessionId");

                    b.HasIndex("StudentModelStudentId");

                    b.HasIndex("StudentId", "RoundType");

                    b.ToTable("InterviewSession", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.QuestionModels", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("TopicId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.SecurityModel.StudentRefreshTokenModel", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("StudentId", "IsRevoked");

                    b.ToTable("StudentRefreshToken", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.StudentAnswerModel", b =>
                {
                    b.Property<Guid>("StudentAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InterviewSessionModelsInterviewSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentAnswerId");

                    b.HasIndex("InterviewSessionId");

                    b.HasIndex("InterviewSessionModelsInterviewSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("StudentAnswer", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.StudentModel", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId");

                    b.HasIndex("Batch");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RollNumber")
                        .IsUnique();

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.StudentSubScriptionModel", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSubscription", (string)null);
                });

            modelBuilder.Entity("AIInterview.Shared.Models.TopicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TopicModel");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.CheatEventModel", b =>
                {
                    b.HasOne("AIInterview.Shared.Models.InterviewSessionModels", "Session")
                        .WithMany()
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIInterview.Shared.Models.InterviewSessionModels", null)
                        .WithMany("CheatEvents")
                        .HasForeignKey("InterviewSessionModelsInterviewSessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.InterviewSessionModels", b =>
                {
                    b.HasOne("AIInterview.Shared.Models.StudentModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIInterview.Shared.Models.StudentModel", null)
                        .WithMany("Sessions")
                        .HasForeignKey("StudentModelStudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.QuestionModels", b =>
                {
                    b.HasOne("AIInterview.Shared.Models.TopicModel", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.SecurityModel.StudentRefreshTokenModel", b =>
                {
                    b.HasOne("AIInterview.Shared.Models.StudentModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.StudentAnswerModel", b =>
                {
                    b.HasOne("AIInterview.Shared.Models.InterviewSessionModels", "Session")
                        .WithMany()
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIInterview.Shared.Models.InterviewSessionModels", null)
                        .WithMany("Answers")
                        .HasForeignKey("InterviewSessionModelsInterviewSessionId");

                    b.HasOne("AIInterview.Shared.Models.QuestionModels", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.StudentSubScriptionModel", b =>
                {
                    b.HasOne("AIInterview.Shared.Models.StudentModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.InterviewSessionModels", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("CheatEvents");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.StudentModel", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AIInterview.Shared.Models.TopicModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
